name: Safety
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # weekly
jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Run Safety CLI to check for vulnerabilities
        uses: pyupio/safety-action@2591cf2f3e67ba68b923f4c92f0d36e281c65023  # v1.0.1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
